### ISSUE TITLE
Service "phpoffice.spreadsheet" not found

### ISSUE THREAD

**Issue by nicohery** [yectep/phpspreadsheet-bundle#17]
I followed the README instructions and when I try to use :

`$newSpreadsheet = $this->get('phpoffice.spreadsheet')->createSpreadsheet();`

I have this error :

> Service "phpoffice.spreadsheet" not found: even though it exists in the app's container, the container inside "App\Controller\MyController" is a smaller service locator that only knows about the "doctrine" ... and "twig" services. Try using dependency injection instead.

There's nothing about "phpoffice.spreadsheet" in my /config/services.yaml
Do I have something to add manually ?

I'm using Symfony 4.4.2

**Comment by Dreeckan** [comment]
You shouldn't use `$this->get('phpoffice.spreadsheet')` to get your service from your controller. 
This works for several core services only.

Instead, you should inject the service in your controller (see [Symfony's autowiring documentation](https://symfony.com/doc/current/service_container/autowiring.html) for a better explanation). 

```php
<?php

namespace App\Controller;

use Yectep\PhpSpreadsheetBundle\Factory;

class MyController
{
    public function __construct(
        Factory $spreadsheetFactory
    ) {
        ...
    }
}
```
Hope this helps :)

**Comment by nicohery** [comment]
I already tried this way. I have this error: 

> Cannot autowire argument $spreadsheetFactory of "App\Controller\MyController::import()": it references class "Yectep\PhpSpreadsheetBundle\Factory" but no such service exists. You should maybe alias this class to the existing "phpoffice.spreadsheet" service.

That's why I tried to strictly follow README explaination...

**Comment by Dreeckan** [comment]
I guess another method would be to create a dedicated service `App\Service\SpreadsheetImporter` for example, and inject it with the right `phpoffice.spreadsheet` service. (That's how we usually use this service)

Or I supposed you tried to use [this way](https://symfony.com/doc/current/controller.html#controller-accessing-services) ?

```yaml
# config/services.yaml
services:
    # ...

    # explicitly configure the service
    App\Controller\MyController:
        public: true
        bind:
            # for any $spreadsheetFactory argument, pass this specific service
            $spreadsheetFactory: '@phpoffice.spreadsheet'
```
